version: '3.5'

services:

  flask-api:
    container_name: app-app
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - "database"

  database:
    image: postgres:10.5
    container_name: postgres
    ports:
      - '8001:5432'
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - './database/init:/docker-entrypoint-initdb.d/'
