version: '3.5'

services:

  flask-api:
    container_name: app-app
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "database"

  database:
    image: postgres:10.5
    container_name: postgres
    ports:
      - '8001:5432'
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - './database/init:/docker-entrypoint-initdb.d/'

  frontend:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3000:80"
    depends_on:
      - "flask-api"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://192.168.99.100:3000
